server.port: 8080
server:
  servlet-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gen_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123456

  rabbitmq: #对于rabbitMQ的支持
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
      # ------- 消息确认配置项 --------
    # 确认消息已发送到交换机
    publisher-confirms: true
    # 确认消息已发送队列
    publisher-returns: true

  redis:
    host: localhost
    port: 6379
    password: jl2012
    database: 0